version: '3'

services:
  frontend:
    build:
      context: ./dashboard_frontend/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
    - app-network
    depends_on:
      - backend
    # environment:
    #   NEXT_PUBLIC_API_URL: http://localhost:8000  # Backend API URL

  backend:
    build:
      context: ./chart_backend
      dockerfile: Dockerfile
    # volumes:
    #   - ./backend:/app
    ports:
      - "8000:8000"
    networks:
    - app-network
    # environment:
    #   DJANGO_SETTINGS_MODULE: myproject.settings

networks:
  app-network:
    driver: bridge
